# Criando variaveis

In [21]:
import pandas as pd

dados = pd.read_csv("../data/aluguel_residencial.csv", sep= ";")

dados["Valor Bruto"] = dados["Valor"] + dados["Condominio"] + dados["IPTU"]

dados["Valor m2"]  = round(dados["Valor"]/dados["Area"],2)

dados["Valor Bruto m2"]  = round(dados["Valor Bruto"]/dados["Area"],2)

casas = ['Casa', "Casa de Vila", "Casa de Condomínio"]
dados["Agregado"]  = dados["Tipo"].apply( lambda x : "Casa" if x in casas else "Apartamento")


dados.head(15)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor Bruto,Valor m2,Valor Bruto m2,Agregado
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0,2260.0,42.50,56.50,Apartamento
1,Casa,Jardim Botânico,2,0,1,100,7000.0,0.0,0.0,7000.0,70.00,70.00,Casa
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0,10331.0,34.67,68.87,Apartamento
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,1210.0,53.33,80.67,Apartamento
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0,1030.0,16.67,21.46,Apartamento
5,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0,1618.0,26.00,32.36,Apartamento
6,Casa de Condomínio,Barra da Tijuca,5,4,5,750,22000.0,0.0,0.0,22000.0,29.33,29.33,Casa
7,Casa de Condomínio,Ramos,2,2,0,65,1000.0,0.0,0.0,1000.0,15.38,15.38,Casa
8,Conjunto Comercial/Sala,Centro,0,3,0,695,35000.0,19193.0,3030.0,57223.0,50.36,82.34,Apartamento
9,Apartamento,Grajaú,2,1,0,70,1500.0,642.0,74.0,2216.0,21.43,31.66,Apartamento
10,Apartamento,Lins de Vasconcelos,3,1,1,90,1500.0,455.0,14.0,1969.0,16.67,21.88,Apartamento
11,Apartamento,Copacabana,1,0,1,40,2000.0,561.0,50.0,2611.0,50.00,65.28,Apartamento
12,Quitinete,Copacabana,1,0,0,27,1800.0,501.0,0.0,2301.0,66.67,85.22,Apartamento
13,Apartamento,Copacabana,4,3,1,243,13000.0,2000.0,803.0,15803.0,53.50,65.03,Apartamento
14,Prédio Inteiro,Botafogo,0,0,0,536,28000.0,0.0,3563.0,31563.0,52.24,58.89,Apartamento

## Como remover variaveis

In [22]:
dt_aux = pd.DataFrame(data= dados[["Agregado","Valor Bruto", "Valor m2", "Valor Bruto m2"]])

#uma das formas
del dt_aux["Agregado"]

#outra forma

dt_aux.pop("Valor Bruto m2")

# Forma mais usada 

dados.drop(["Valor Bruto", "Valor Bruto m2"], axis= 1, inplace= True)

dados.head(10)

dados.to_csv("../data/aluguel_residencial.csv", sep= ";")